#!/usr/bin/env perl
# Generate portable C definitions for the resources declared by common/ref.h.
# SPDX-License-Identifier: GPL-2.0-or-later

use strict;
use warnings;
use File::Basename qw(basename);

@ARGV or die "Usage: $0 FILE...\n";
print "/* Generated by auxdir/embed_text.pl. Do not edit. */\n";
print "#include <stddef.h>\n\n";

my %symbols;
for my $path (@ARGV) {
    my $symbol = basename($path);
    $symbol =~ s/[^a-zA-Z0-9_]/_/g;
    die "Duplicate resource name: $path\n" if $symbols{$symbol}++;

    open my $input, '<:raw', $path or die "Cannot open $path: $!\n";
    print "const unsigned char slurm_static_${symbol}[] = {\n";
    while (1) {
        my $count = read $input, my $bytes, 16;
        defined $count or die "Cannot read $path: $!\n";
        last unless $count;
        print "\t", join(', ', map { sprintf '0x%02x', $_ }
            unpack 'C*', $bytes), ",\n";
    }
    close $input or die "Cannot close $path: $!\n";
    # The sentinel makes empty resources valid C; it is excluded from the size.
    print "\t0\n};\n";
    print "const size_t slurm_static_${symbol}_size =\n";
    print "\tsizeof(slurm_static_${symbol}) - 1;\n\n";
}
